# Generated by Django 2.1 on 2019-11-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('can_add_article', 'add article'),)},
        ),
    ]
